# Generated by Django 2.0.5 on 2018-06-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='upvote',
        ),
    ]
