# Generated by Django 2.0.5 on 2018-06-16 01:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='votelist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
