# Generated by Django 2.0.5 on 2018-06-16 01:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_votelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votelist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
