# Generated by Django 2.0.5 on 2018-06-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180616_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='votelist',
        ),
    ]
