# Generated by Django 2.0.6 on 2018-06-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_votenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
