# Generated by Django 2.0.6 on 2018-06-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votenames',
            field=models.TextField(),
        ),
    ]
