# Generated by Django 2.0.6 on 2018-06-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180616_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default=True, max_length=25),
        ),
    ]
