# Generated by Django 2.0.6 on 2018-06-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180617_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=True, max_length=25, null=True),
        ),
    ]
